### ISSUE TITLE
계정 정보가 짤립니다.

### ISSUE THREAD

**Issue by ujcb52** [gelius7/aws-switch-accesskey#1]
https://github.com/gelius7/aws-switch-accesskey/blob/572159ea200d91255210c54f4250b85e20cf4f26/aao#L152

maxResults=999

값이 없으면 20개 정도 계정 정보에서 짤리는 듯합니다.

**Comment by gelius7** [comment]
가능하시다면 PR 로 부탁해요 ^^

**Comment by ujcb52** [comment]
권한이 없는듯요? ㅎ

**Comment by gelius7** [comment]
@ujcb52 여기가 개인 공간이라서 그런가봅니다. https://github.com/heyjam/aws-switch-accesskey 로 만들었어요
